# Generated by Django 2.2 on 2019-05-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('product_date', models.DateField()),
            ],
        ),
    ]
