# Generated by Django 2.2 on 2019-05-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
